### ISSUE TITLE
Add .gitignore file and get rid of *.java file from your repo

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/java#1]
And add at least this line in the file

*.java

Also.... do "git rm" on the current *.java file since it is unnecessarily added to your repo.

**Comment by ajkim0630** [comment]
which java file do i get rid of

**Comment by jybluekim** [comment]
Per our discussion I think you need to add *.class in .gitignore (not *.java).

**Comment by ajkim0630** [comment]
done by myself
